### PR TITLE
Add `rust-analyzer`

### PR DESCRIPTION
**Pull request by Guldoman**
Needs that lite-xl/lite-xl-plugin-manager#37 gets fixed.

More platforms could be added.

### CODE REVIEW

**Comment by adamharrison** [comment]
Can you also modify the README? It's not auto-generated on this one.

**Comment by Guldoman** [comment]
Converting to draft, as we might need to manually set executable permissions.

**Comment by Guldoman** [comment]
Ah wait, let me update to the latest version.

**Comment by Guldoman** [comment]
Alright, good to go.

**Pull request merged**
